name: Extract Docker Image and Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract files from Docker image
      run: |
        docker pull earnfm/earnfm-client
        CONTAINER_ID=$(docker create earnfm/earnfm-client)
        mkdir -p app_files
        docker cp $CONTAINER_ID:/app ./app_files/
        sudo chown -R $(id -u):$(id -g) ./app_files
        docker rm $CONTAINER_ID

    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Compress files
      run: cd app_files && zip -r ../earnfm.zip .

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: earnfm.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}