name: Scheduled Docker Extract and Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'  # 每两天UTC时间00:00运行

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract Docker image digest
      run: |
        docker pull earnfm/earnfm-client
        DIGEST=$(docker inspect earnfm/earnfm-client --format '{{index .RepoDigests 0}}' | cut -d'@' -f2)
        echo "DIGEST=${DIGEST}" >> $GITHUB_ENV
        echo "TAG_NAME=EarnFM-${DIGEST}" >> $GITHUB_ENV

    - name: Create and push tags
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag $TAG_NAME
        git push origin $TAG_NAME
        git tag -f latest
        git push origin latest --force

    - name: Extract files from Docker image
      run: |
        mkdir -p app_files
        CONTAINER_ID=$(docker create earnfm/earnfm-client)
        docker cp $CONTAINER_ID:/app ./app_files/
        sudo chown -R $(id -u):$(id -g) ./app_files
        docker rm $CONTAINER_ID

    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Compress files
      run: cd app_files && zip -r ../earnfm.zip .

    - name: Upload to Digest Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: earnfm-client
        files: earnfm.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to Latest Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: earnfm-client
        files: earnfm.zip
        overwrite: true  # 覆盖已有latest发布
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}